### ISSUE TITLE
How to deal with missing extensions? 

### ISSUE THREAD

**Issue by tensorfoo** [ticofab/android-gpx-parser#29]
Hi, thanks so much for this nice library! Quick question, my GPX files also have a HR field under TrackPointExtension (to go along with the usual lat/long/time fields). I'm trying to figure out the best way to go add the HR field to the TrackPoints returned by the library.

**Comment by ticofab** [comment]
Hey @tensorfoo ! The rule is: If fiends are part of the official GPX standard, I'm happy to include them in the library - please open a PR :) Otherwise, I imagine that the only way would be to fork the project, add the extension to your fork and link to your version in your app. 
Closing the issue for now, feel free to reopen.
